on:
  workflow_dispatch:

jobs:
  build-gettext:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
        
    steps:
      - uses: msys2/setup-msys2@v2
        with:
          msystem: mingw64
          update: true
          install: mingw-w64-x86_64-gcc make

      - name: Download libiconv
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: libiconv.yml 
          workflow_conclusion: success
          name: libiconv-${{ vars.LIBICONV_VERSION }}-win64
          path: /builddeps
          if_no_artifact_found: fail
          
      - name: Download
        run: | 
          curl https://ftp.gnu.org/pub/gnu/gettext/gettext-${{ vars.GETTEXT_VERSION }}.tar.gz -o ./gettext-${{ vars.GETTEXT_VERSION }}.tar.gz
          tar zxvf gettext-${{ vars.GETTEXT_VERSION }}.tar.gz

      - name: Configure
        run: | 
          cd gettext-${{ vars.GETTEXT_VERSION }}/gettext-runtime
          ./configure --prefix=$(pwd)/winpgbuild --disable-static --disable-dependency-tracking --enable-silent-rules --with-libiconv-prefix=/builddeps --disable-rpath --enable-nls --disable-csharp --disable-java --enable-threads=windows --enable-relocatable
          
      - name: Build
        run: | 
          cd gettext-${{ vars.GETTEXT_VERSION }}/gettext-runtime
          make all

      - name: Install
        run: |
          cd gettext-${{ vars.GETTEXT_VERSION }}/gettext-runtime
          make install

          cp winpgbuild/lib/libintl.dll.a winpgbuild/lib/libintl.lib
          cp winpgbuild/lib/libasprintf.dll.a winpgbuild/lib/libasprintf.lib

      - name: Upload Source
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          name: gettext-${{ vars.GETTEXT_VERSION }}-src
          path: gettext-${{ vars.GETTEXT_VERSION }}.tar.gz
          
      - name: Upload Binaries
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          name: gettext-${{ vars.GETTEXT_VERSION }}-win64
          path: gettext-${{ vars.GETTEXT_VERSION }}/gettext-runtime/winpgbuild
