on:
  workflow_dispatch:

jobs:
  build-icu:
    runs-on: windows-latest
    steps:
      - uses: ilammy/msvc-dev-cmd@v1

      - name: Download
        run: |
          curl -L https://github.com/unicode-org/icu/releases/download/release-$(echo ${{ vars.ICU_VERSION }} | sed 's/\./-/g')/icu4c-$(echo ${{ vars.ICU_VERSION }} | sed 's/\./_/g')-src.tgz -o ./icu4c-${{ vars.ICU_VERSION }}.tar.gz
          tar zxvf ./icu4c-${{ vars.ICU_VERSION }}.tar.gz
        shell: bash

      - name: Build
        run: |
          cd icu
          devenv.com source\allinone\allinone.sln /build "Release|x64"

      - name: Install
        run: |
          cd icu

          mkdir \icu

          mkdir \icu\bin64
          copy bin64\* \icu\bin64\

          mkdir \icu\include
          mkdir \icu\include/unicode
          copy include\unicode\* \icu\include\unicode\/

          mkdir \icu\lib64
          copy lib64\* \icu\lib64\

      - name: Upload Source
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          name: icu-${{ vars.ICU_VERSION }}-src
          path: icu4c-${{ vars.ICU_VERSION }}.tar.gz

      - name: Upload Binaries
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          name: icu-${{ vars.ICU_VERSION }}-win64
          path: /icu
