on:
  workflow_dispatch:

jobs:
  build-krb5:
    runs-on: windows-latest
    steps:
      - uses: ilammy/msvc-dev-cmd@v1

      - name: Download
        run: |
          curl https://kerberos.org/dist/krb5/1.21/krb5-${{ vars.KRB5_VERSION }}.tar.gz -o ./krb5-${{ vars.KRB5_VERSION }}.tar.gz
          tar zxvf krb5-${{ vars.KRB5_VERSION }}.tar.gz

      - name: Configure
        run: |
          cd krb5-${{ vars.KRB5_VERSION }}\src
          nmake -f Makefile.in prep-windows

      - name: Build
        run: |
          cd krb5-${{ vars.KRB5_VERSION }}\src
          $env:PATH += ";" + $env:WindowsSdkVerBinPath + "\x86"
          nmake NODEBUG=1

      - name: Install
        # We're only doing a 64 bit build, so we need to tweak things at the
        # end of the installation to make it look as it would if we had built
        # both 32 and 64 bit together.
        run: |
          mkdir \krb5
          cd krb5-${{ vars.KRB5_VERSION }}\src
          $env:KRB_INSTALL_DIR = "\krb5"
          nmake install NODEBUG=1

          mkdir \krb5\lib\amd64
          move \krb5\lib\*.lib \krb5\lib\amd64\

      - name: Upload Source
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          name: krb5-${{ vars.KRB5_VERSION }}-src
          path: krb5-${{ vars.KRB5_VERSION }}.tar.gz

      - name: Upload Binaries
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          name: krb5-${{ vars.KRB5_VERSION }}-win64
          path: /krb5
