on:
  workflow_dispatch:

jobs:
  build-libiconv:
    runs-on: windows-latest
    
    defaults:
      run:
        shell: msys2 {0}
        
    steps:
      - uses: msys2/setup-msys2@v2
        with:
          msystem: mingw64
          update: true
          install: mingw-w64-x86_64-gcc make
          
      - name: Download
        run: | 
          curl https://ftp.gnu.org/pub/gnu/libiconv/libiconv-${{ vars.LIBICONV_VERSION }}.tar.gz -o ./libiconv-${{ vars.LIBICONV_VERSION }}.tar.gz
          tar zxvf libiconv-${{ vars.LIBICONV_VERSION }}.tar.gz

      - name: Configure
        run: | 
          cd libiconv-${{ vars.LIBICONV_VERSION }}
          ./configure --prefix=./build
          
      - name: Build
        run: | 
          cd libiconv-${{ vars.LIBICONV_VERSION }}
          make all

      - name: Install
        run: |
          cd libiconv-${{ vars.LIBICONV_VERSION }}
          make install

          cp build/lib/libiconv.dll.a build/lib/iconv.lib
          cp build/lib/libcharset.dll.a build/lib/charset.lib

      - name: Upload
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: libiconv-${{ vars.LIBICONV_VERSION }}-win64
          path: libiconv-${{ vars.LIBICONV_VERSION }}/build
