on:
  workflow_dispatch:

jobs:
  build-libiconv:
    runs-on: windows-latest
    steps:
      - name: Download
        run: | 
          curl https://ftp.gnu.org/pub/gnu/libiconv/libiconv-${{ vars.LIBICONV_VERSION }}.tar.gz -o ./libiconv-${{ vars.LIBICONV_VERSION }}.tar.gz
          tar zxvf libiconv-${{ vars.LIBICONV_VERSION }}.tar.gz

      - name: Configure
        run: | 
          cd libiconv-${{ vars.LIBICONV_VERSION }}
          ./configure --prefix=/libiconv
        shell: bash
          
      - name: Build
        run: | 
          cd libiconv-${{ vars.LIBICONV_VERSION }}
          make all
        shell: bash

      - name: Install
        run: |
          cd libiconv-${{ vars.LIBICONV_VERSION }}
          make install

          cp /libiconv/lib/libiconv.dll.a /libiconv/lib/iconv.lib
          cp /libiconv/lib/libcharset.dll.a /libiconv/lib/charset.lib
        shell: bash

      - name: Upload
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: libiconv-${{ vars.LIBICONV_VERSION }}-win64
          path: /libiconv
