on:
  workflow_dispatch:

jobs:
  build-lz4:
    runs-on: windows-latest
    steps:
      - uses: microsoft/setup-msbuild@v2

      - name: Download
        run: |
          curl -L https://github.com/lz4/lz4/releases/download/v${{ vars.LZ4_VERSION }}/lz4-${{ vars.LZ4_VERSION }}.tar.gz -o ./lz4-${{ vars.LZ4_VERSION }}.tar.gz
          tar zxvf lz4-${{ vars.LZ4_VERSION }}.tar.gz

      - name: Configure
        run: |
          cd lz4-${{ vars.LZ4_VERSION }}
          cmake -B build -D CMAKE_INSTALL_PREFIX=/lz4 build/cmake

      - name: Build
        run: |
          cd lz4-${{ vars.LZ4_VERSION }}
          cmake --build build --config Release

      - name: Install
        run: |
          cd lz4-${{ vars.LZ4_VERSION }}
          cmake --install build
          # backward compatibility with src/tools/msvc build for PG <= 16
          copy \lz4\lib\lz4.lib \lz4\lib\liblz4.lib

      - name: Upload Source
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          name: lz4-${{ vars.LZ4_VERSION }}-src
          path: lz4-${{ vars.LZ4_VERSION }}.tar.gz

      - name: Upload Binaries
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          name: lz4-${{ vars.LZ4_VERSION }}-win64
          path: /lz4
