on:
  workflow_dispatch:

jobs:
  build-openssl:
    runs-on: windows-latest
    steps:
      - uses: ilammy/msvc-dev-cmd@v1
            
      - name: Download
        run: | 
          curl https://www.openssl.org/source/openssl-${{ vars.OPENSSL_VERSION }}.tar.gz -o ./openssl-${{ vars.OPENSSL_VERSION }}.tar.gz
          tar zxvf openssl-${{ vars.OPENSSL_VERSION }}.tar.gz

      - name: Configure
        run: | 
          cd openssl-${{ vars.OPENSSL_VERSION }}
          perl Configure VC-WIN64A no-asm --prefix=\openssl no-ssl3 no-comp
          
      - name: Build
        run: | 
          cd openssl-${{ vars.OPENSSL_VERSION }}
          nmake

      - name: Test
        run: | 
          cd openssl-${{ vars.OPENSSL_VERSION }}
          nmake test

      - name: Install
        run: |
          mkdir \openssl
          cd openssl-${{ vars.OPENSSL_VERSION }}
          nmake install

      - name: Create pkgconfig File
        run: |
          mkdir \openssl\lib\pkgconfig

          >> \openssl\lib\pkgconfig\openssl.pc echo prefix=${pcfiledir}/../..
          >> \openssl\lib\pkgconfig\openssl.pc echo exec_prefix=${prefix}
          >> \openssl\lib\pkgconfig\openssl.pc echo libdir=${prefix}/lib
          >> \openssl\lib\pkgconfig\openssl.pc echo includedir=${prefix}/include
          >> \openssl\lib\pkgconfig\openssl.pc echo.
          >> \openssl\lib\pkgconfig\openssl.pc echo Name: openssl
          >> \openssl\lib\pkgconfig\openssl.pc echo Description: openssl encryption library
          >> \openssl\lib\pkgconfig\openssl.pc echo Version: ${{ vars.OPENSSL_VERSION }}
          >> \openssl\lib\pkgconfig\openssl.pc echo Libs: -L${libdir} -lcrypto -lssl
          >> \openssl\lib\pkgconfig\openssl.pc echo Cflags: -I${includedir}
        shell: cmd

      - name: Upload Source
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          name: openssl-${{ vars.OPENSSL_VERSION }}-src
          path: openssl-${{ vars.OPENSSL_VERSION }}.tar.gz
          
      - name: Upload Binaries
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          name: openssl-${{ vars.OPENSSL_VERSION }}-win64
          path: /openssl
