on:
  workflow_dispatch:

jobs:
  build-ossp-uuid:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
        
    steps:
      - uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: mingw-w64-ucrt-x86_64-gcc automake autoconf pkg-config make zip patch tar
          
      - name: Download
        # We get this from the Debian repo, as OSSP is basically unavailable these days
        run: | 
          curl https://salsa.debian.org/debian/ossp-uuid/-/archive/upstream/${{ vars.OSSP_UUID_VERSION }}/ossp-uuid-upstream-${{ vars.OSSP_UUID_VERSION }}.tar.gz -o ./ossp-uuid-upstream-${{ vars.OSSP_UUID_VERSION }}.tar.gz
          tar zxvf ossp-uuid-upstream-${{ vars.OSSP_UUID_VERSION }}.tar.gz

      - name: Configure
        run: | 
          cd ossp-uuid-upstream-${{ vars.OSSP_UUID_VERSION }}
          ./configure --prefix=$(pwd)/winpgbuild
        shell: bash
          
      - name: Build
        run: | 
          cd ossp-uuid-upstream-${{ vars.OSSP_UUID_VERSION }}
          make all
        shell: bash

      - name: Install
        # Manual installation, as .exe extensions aren't handled properly
        run: |
          cd ossp-uuid-upstream-${{ vars.OSSP_UUID_VERSION }}
          mkdir winpgbuild
          mkdir winpgbuild/bin
          mkdir winpgbuild/include
          mkdir winpgbuild/lib

          cp .libs/uuid.exe winpgbuild/bin
          cp uuid.h winpgbuild/include
          cp .libs/libuuid.a winpgbuild/lib
          cp .libs/libuuid.a winpgbuild/lib/uuid.lib
          cp .libs/libuuid.la winpgbuild/lib
          cp .libs/libuuid.lai winpgbuild/lib

      - name: Create pkgconfig File
        run: |
          cd ossp-uuid-upstream-${{ vars.OSSP_UUID_VERSION }}
          mkdir lib\pkgconfig

          >> lib\pkgconfig\ossp-uuid.pc echo prefix=${pcfiledir}/../..
          >> lib\pkgconfig\ossp-uuid.pc echo exec_prefix=${prefix}
          >> lib\pkgconfig\ossp-uuid.pc echo libdir=${prefix}/lib
          >> lib\pkgconfig\ossp-uuid.pc echo includedir=${prefix}/include
          >> lib\pkgconfig\ossp-uuid.pc echo.
          >> lib\pkgconfig\ossp-uuid.pc echo Name: ossp-uuid
          >> lib\pkgconfig\ossp-uuid.pc echo Description: ossp uuid library
          >> lib\pkgconfig\ossp-uuid.pc echo Version: ${{ vars.OSSP_UUID_VERSION }}
          >> lib\pkgconfig\ossp-uuid.pc echo Libs: -L${libdir} -luuid
          >> lib\pkgconfig\ossp-uuid.pc echo Cflags: -I${includedir}
        shell: cmd

      - name: Upload Source
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          name: ossp-uuid-upstream-${{ vars.OSSP_UUID_VERSION }}-src
          path: ossp-uuid-upstream-${{ vars.OSSP_UUID_VERSION }}.tar.gz
          
      - name: Upload Binaries
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          name: ossp-uuid-${{ vars.OSSP_UUID_VERSION }}-win64
          path: ossp-uuid-upstream-${{ vars.OSSP_UUID_VERSION }}/winpgbuild
