on:
  workflow_dispatch:

jobs:
  build-ossp-uuid:
    runs-on: windows-latest
    steps:
      - name: Download
        # We get this from the Debian repo, as OSSP is basically unavailable these days
        run: | 
          curl https://salsa.debian.org/debian/ossp-uuid/-/archive/upstream/${{ vars.OSSP_UUID_VERSION }}/ossp-uuid-upstream-${{ vars.OSSP_UUID_VERSION }}.tar.gz -o ./ossp-uuid-${{ vars.OSSP_UUID_VERSION }}.tar.gz
          tar zxvf ossp-uuid-${{ vars.OSSP_UUID_VERSION }}.tar.gz
        shell: bash

      - name: Configure
        run: | 
          cd ossp-uuid-${{ vars.OSSP_UUID_VERSION }}
          ./configure --prefix=/ossp-uuid
        shell: bash
          
      - name: Build
        run: | 
          cd ossp-uuid-${{ vars.OSSP_UUID_VERSION }}
          make all
        shell: bash

      - name: Install
        run: |
          cd ossp-uuid-${{ vars.OSSP_UUID_VERSION }}
          make install
        shell: bash

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: ossp-uuid-${{ vars.OSSP_UUID_VERSION }}-win64
          path: /ossp-uuid
