on:
  workflow_dispatch:

jobs:
  build-postgresql:
    runs-on: windows-latest
    steps:
      - name: Download openssl
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: openssl.yml 
          workflow_conclusion: success
          name: openssl-${{ vars.OPENSSL_VERSION }}-win64
          path: /build/openssl
          if_no_artifact_found: fail

      - name: Download krb5
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: krb5.yml 
          workflow_conclusion: success
          name: krb5-${{ vars.KRB5_VERSION }}-win64
          path: /build/krb5
          if_no_artifact_found: fail
          
      - name: Download zlib
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: zlib.yml 
          workflow_conclusion: success
          name: zlib-${{ vars.ZLIB_VERSION }}-win64
          path: /build/zlib
          if_no_artifact_found: fail
