on:
  workflow_dispatch:

jobs:
  build-zlib:
    runs-on: windows-latest
    steps:
      - name: Retrieve the source code
        run: | 
          echo "Retrieving zlib version ${{ vars.ZLIB_VERSION }}."
          curl https://zlib.net/zlib-${{ vars.ZLIB_VERSION }}.tar.gz -o ./zlib-${{ vars.ZLIB_VERSION }}.tar.gz
          tar -zxvf zlib-${{ vars.ZLIB_VERSION }}.tar.gz
          
      - name: Add msbuild to the path
        uses: microsoft/setup-msbuild@v2
        
      - name: Build the code
        run: | 
          echo "Building zlib version ${{ vars.ZLIB_VERSION }}."
          cd zlib-${{ vars.ZLIB_VERSION }}
          mkdir ${{ vars.GITHUB_WORKSPACE }}/build
          mkdir ${{ vars.GITHUB_WORKSPACE }}/build/zlib
          cmake -DCMAKE_INSTALL_PREFIX=${{ vars.GITHUB_WORKSPACE }}/build/zlib -G "Visual Studio 17 2022" .
          msbuild ALL_BUILD.vcxproj /p:Configuration=Release

      - name: Test the code
        run: | 
          echo "Testing zlib version ${{ vars.ZLIB_VERSION }}."
          cd zlib-${{ vars.ZLIB_VERSION }}
          msbuild RUN_TESTS.vcxproj /p:Configuration=Release
