on:
  workflow_dispatch:

jobs:
  build-zstd:
    runs-on: windows-latest
    steps:
      - uses: microsoft/setup-msbuild@v2
      
      - name: Download
        run: | 
          curl -L https://github.com/facebook/zstd/releases/download/v${{ vars.ZSTD_VERSION }}/zstd-${{ vars.ZSTD_VERSION }}.tar.gz -o ./zstd-${{ vars.ZSTD_VERSION }}.tar.gz
          tar zxvf zstd-${{ vars.ZSTD_VERSION }}.tar.gz

      - name: Configure
        run: | 
          cd zstd-${{ vars.ZSTD_VERSION }}
          devenv.com /upgrade build\VS2010\zstd.sln

      - name: Build
        run: | 
          cd zstd-${{ vars.ZSTD_VERSION }}
          msbuild build\VS2010\zstd.sln -target:libzstd-dll /property:Configuration=Release /property:Platform=x64

      - name: Install
        run: |
          cd zstd-${{ vars.ZSTD_VERSION }}
          
          mkdir \zstd
          
          mkdir \zstd\bin
          copy build\VS2010\bin\x64_Release\libzstd.dll \zstd\bin\
          copy build\VS2010\bin\x64_Release\libzstd.pdb \zstd\bin\

          mkdir \zstd\include
          copy lib\*.h \zstd\include\

          mkdir \zstd\lib
          copy build\VS2020\bin\x64_Release\libzstd.lib \zstd\lib\

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          name: zstd-${{ vars.ZSTD_VERSION }}-win64
          path: /zstd
