on:
  workflow_dispatch:

jobs:
  build-zstd:
    runs-on: windows-latest
    steps:
      - uses: microsoft/setup-msbuild@v2
      - uses: ilammy/msvc-dev-cmd@v1

      - name: Download
        run: |
          curl -L https://github.com/facebook/zstd/releases/download/v${{ vars.ZSTD_VERSION }}/zstd-${{ vars.ZSTD_VERSION }}.tar.gz -o ./zstd-${{ vars.ZSTD_VERSION }}.tar.gz
          tar zxvf zstd-${{ vars.ZSTD_VERSION }}.tar.gz

      - name: Configure
        run: |
          cd zstd-${{ vars.ZSTD_VERSION }}
          # With cmake there's VS 2022 msbuild issue, recently fixed
          # https://github.com/facebook/zstd/commit/65ab6c26
          # so use meson
          pip install meson
          meson setup build-meson ./build/meson --wipe --prefix=/zstd --buildtype=release

      - name: Build
        run: |
          cd zstd-${{ vars.ZSTD_VERSION }}
          meson compile -C build-meson

      - name: Install
        run: |
          cd zstd-${{ vars.ZSTD_VERSION }}
          meson install -C build-meson
          # backward compatibility with src/tools/msvc build for PG <= 16
          copy \zstd\lib\zstd.lib \zstd\lib\libzstd.lib

      - name: Upload Source
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          name: zstd-${{ vars.ZSTD_VERSION }}-src
          path: zstd-${{ vars.ZSTD_VERSION }}.tar.gz

      - name: Upload Binaries
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          name: zstd-${{ vars.ZSTD_VERSION }}-win64
          path: /zstd
